### ISSUE TITLE
Cardiac MRN RDF graph to Token RDF graph

### ISSUE THREAD

**Issue by andredekker** [andredekker/BigMachine#7]
Suggested (same for Cancer)
- [x] Create an empty graph ("MRN2Token") within my RDF store and upload the tokens from the Turtle file from #3 
- [x] Create an empty graph ("Token") and given my MRN graph and my MRN2Token graph insert the triples using the tokens. An example is the below SPARQL query.
- [ ] Push triples to SPARQL endpoint of #6 

```
PREFIX roo:<http://www.cancerdata.org/roo/>
PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

INSERT {?token a ncit:C16960. } WHERE 
{
    SERVICE <http://localhost:9999/bigdata/namespace/MRN/sparql> 
            {
              _:cardiacPatient roo:100042 ?mrn.
            }
    SERVICE <http://localhost:9999/bigdata/namespace/MRN2Token/sparql> 
            {
              _:mrnToken roo:100042 ?mrn.
              ?token roo:100318 _:mrnToken.            
            }
.}
```

**Comment by jduhamel** [comment]
Informative. ;)

**Comment by jduhamel** [comment]
As a researcher, I need to have access to the tokens of cardiac patients, I also need the ability to map from a research Token to a MRN patients.

Given a MRN I need to be able to access it's Research token.
Given a Research token I need to be able to map back to the MRN

Create a graph that contains MRN from token
Create a graph that contains Token from MRN

**Comment by andredekker** [comment]
Suggested (same for Cancer)
- [ ] Create an empty graph ("MRN2Token") within my RDF store and upload the tokens from the Turtle file from #3 
- [ ] Create an empty graph ("Token") and given my MRN graph and my MRN2Token graph insert the triples using the tokens. An example is the following SPARQL query:

```
PREFIX roo:<http://www.cancerdata.org/roo/>
PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

INSERT {?token a ncit:C16960. } WHERE 
{
    SERVICE <http://localhost:9999/bigdata/namespace/MRN/sparql> 
            {
              _:cardiacPatient roo:100042 ?mrn.
            }
    SERVICE <http://localhost:9999/bigdata/namespace/MRN2Token/sparql> 
            {
              _:mrnToken roo:100042 ?mrn.
              ?token roo:100318 _:mrnToken.            
            }
.}
```
